baseURL = "/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-tw"

# 网站语言, 仅在这里 CN 大写
languageCode = "zh-TW"

# 是否包括中日韩文字
hasCJKLanguage = true

# 网站标题
title = "快樂肥宅 Simen"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "DoIt"

[params]
# DoIt 主题版本
version = "0.2.X"

[menu]
[[menu.main]]
identifier = "posts"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
name = "文章"
post = ""
url = "/posts/"
# 当你将鼠标悬停在此菜单链接上时, 将显示的标题
title = ""
weight = 1
[[menu.main]]
identifier = "tags"
name = "標籤"
post = ""
pre = ""
title = ""
url = "/tags/"
weight = 2
[[menu.main]]
identifier = "categories"
name = "分類"
post = ""
pre = ""
title = ""
url = "/categories/"
weight = 3

# Hugo 解析文档的配置
[markup]
# 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
# false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false

[params.home.profile]
# Gravatar 邮箱, 用于优先在主页显示的头像
gravatarEmail = ""
# 主页显示头像的 URL
# avatarURL = "/images/18+.png"

# DoIt 更改 | 0.2.0 文章页面的分享信息设置
[params.page.share]

Facebook = true
Twitter = true
enable = true

[params.social]
[params.social.Mastodon]
# 排列图标时的权重 (权重越大, 图标的位置越靠后)
# weight = 0
# # 你的社交 ID
# id = "@xxxx"
# # 你的社交链接的前缀
# prefix = "https://mastodon.social/"
# # 当鼠标停留在图标上时的提示内容

# DoIt 更改 | 0.2.0 评论系统设置
[params.page.comment]
enable = true

[params.page.comment.disqus]
# DoIt 新增 | 0.1.1
enable = true
# Disqus 的 shortname, 用来在文章中启用 Disqus 评论系统
shortname = "simenstack"
